In [1]:
from bs4 import BeautifulSoup

html_doc = open('sample-data.html', 'r')

soup = BeautifulSoup(html_doc, 'html.parser')

In [2]:
soup.prettify()

'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n <head>\n  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">\n   <meta content="Report generated by Flip Side Racing Software www.flipsideracing.org" name="description">\n    <style type="text/css">\n     p {\n\t\t  \n\t\t  background-color: white;\n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  font-weight: normal;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t}\n\t\ttd {\n\t\t  \n\t\t  background-color: white;\n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  font-weight: normal;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t}\n\t\tth {\n\t\t  \n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t  background-color: white;\n\t\t  font-weight: normal;\n\t\t}\n\t\t.gtd td {\n\t\t  \n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t  background-color: #cccccc;\n\t\t  font-weight: normal;\n\t\t}\n\t\t.gth {\n\t\t  \n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t  background-color: #cccccc;\n\t\t  font-weight: normal;\n\t\t}\n\t\t.htd td {\n\t\t  \n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  font-weight: bold;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t  background-color: #ffcc66;\n\t\t}\n\t\t.hth th {\n\t\t  \n\t\t  color: black;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 12px;\n\t\t  font-weight: bold;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t  background-color: #ffcc66;\n\t\t}\n\t\t.ttd td {\n\t\t  \n\t\t  background-color: white;\n\t\t  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;\n\t\t  font-size: 14px;\n\t\t  font-weight: bold;\n\t\t  letter-spacing: 2px;\n\t\t  padding-left: 1em;\n\t\t  padding-right: 1em;\n\t\t  color: red;\n\t\t}\n\t\tspan.ibb {\n\t\t  \n\t\t  background-color: #99ccff;\n\t\t}\n    </style>\n    <title>\n     Race Results\n    </title>\n   </meta>\n  </meta>\n </head>\n <body>\n  <table border="0" cellpadding="0" cellspacing="0" width="100%">\n   <tbody align="right">\n    <tr>\n     <td align="center" colspan="7">\n      <img alt="Club logo" src="exampleLogo.jpg"/>\n     </td>\n    </tr>\n    <tr class="ttd">\n     <td align="center" colspan="7">\n      Power Racing Series\n     </td>\n    </tr>\n    <tr>\n     <td align="center" colspan="7">\n      2017 New York Sprint 2 Main 2017-09-23 15:07:22\n     </td>\n    </tr>\n    <tr>\n     <td align="center" colspan="7">\n      Lap\n     </td>\n    </tr>\n    <tr>\n     <td align="center" colspan="7">\n      Main\n     </td>\n    </tr>\n    <tr>\n     <td>\n      <br>\n      </br>\n     </td>\n    </tr>\n   </tbody>\n  </table>\n  <table border="0" cellpadding="0" cellspacing="0" width="100%">\n   <thead align="right" class="hth">\n    <tr>\n     <th>\n      Position\n     </th>\n     <th>\n      Laps\n     </th>\n     <th>\n      Time\n     </th>\n     <th>\n      Average\n     </th>\n     <th>\n      Best\n     </th>\n     <th>\n      Laps Leading\n     </th>\n     <th>\n      Name\n     </th>\n    </tr>\n   </thead>\n   <tbody align="right">\n    <tr>\n     <td>\n      1\n     </td>\n     <td>\n      30\n     </td>\n     <td>\n      11:20.014\n     </td>\n     <td>\n      22.667\n     </td>\n     <td>\n      30/19.501\n     </td>\n     <td>\n      11\n     </td>\n     <td>\n      Atomic Chibi\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      2\n     </td>\n     <td>\n      30\n     </td>\n     <td>\n      11:22.749\n     </td>\n     <td>\n      22.758\n     </td>\n     <td>\n      29/19.084\n     </td>\n     <td>\n      8\n     </td>\n     <td>\n      Lego Car\n     </td>\n    </tr>\n    <tr>\n     <td>\n      3\n     </td>\n     <td>\n      30\n     </td>\n     <td>\n      11:36.034\n     </td>\n     <td>\n      23.201\n     </td>\n     <td>\n      2/19.707\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      RU Greasy\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      4\n     </td>\n     <td>\n      28\n     </td>\n     <td>\n      11:29.735\n     </td>\n     <td>\n      24.633\n     </td>\n     <td>\n      17/21.990\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      The Bus\n     </td>\n    </tr>\n    <tr>\n     <td>\n      5\n     </td>\n     <td>\n      28\n     </td>\n     <td>\n      11:34.684\n     </td>\n     <td>\n      24.81\n     </td>\n     <td>\n      23/22.117\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Amazon Box\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      6\n     </td>\n     <td>\n      27\n     </td>\n     <td>\n      11:36.440\n     </td>\n     <td>\n      25.794\n     </td>\n     <td>\n      10/22.462\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Blue Meanie\n     </td>\n    </tr>\n    <tr>\n     <td>\n      7\n     </td>\n     <td>\n      27\n     </td>\n     <td>\n      11:39.702\n     </td>\n     <td>\n      25.915\n     </td>\n     <td>\n      15/19.236\n     </td>\n     <td>\n      2\n     </td>\n     <td>\n      Electric Koolaid Acid Test\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      8\n     </td>\n     <td>\n      22\n     </td>\n     <td>\n      11:26.011\n     </td>\n     <td>\n      31.182\n     </td>\n     <td>\n      4/26.520\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      MAV 721\n     </td>\n    </tr>\n    <tr>\n     <td>\n      9\n     </td>\n     <td>\n      21\n     </td>\n     <td>\n      11:35.918\n     </td>\n     <td>\n      33.139\n     </td>\n     <td>\n      14/31.678\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Smoothie\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      10\n     </td>\n     <td>\n      20\n     </td>\n     <td>\n      11:43.065\n     </td>\n     <td>\n      35.153\n     </td>\n     <td>\n      13/30.852\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Maximum Overdrive\n     </td>\n    </tr>\n    <tr>\n     <td>\n      11\n     </td>\n     <td>\n      19\n     </td>\n     <td>\n      11:34.858\n     </td>\n     <td>\n      36.571\n     </td>\n     <td>\n      18/20.315\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      FUBAR\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      12\n     </td>\n     <td>\n      16\n     </td>\n     <td>\n      8:15.778\n     </td>\n     <td>\n      30.986\n     </td>\n     <td>\n      9/25.756\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Aerobot\n     </td>\n    </tr>\n    <tr>\n     <td>\n      13\n     </td>\n     <td>\n      15\n     </td>\n     <td>\n      11:36.035\n     </td>\n     <td>\n      46.402\n     </td>\n     <td>\n      7/28.310\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Train Wrecks\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      14\n     </td>\n     <td>\n      15\n     </td>\n     <td>\n      11:40.800\n     </td>\n     <td>\n      46.72\n     </td>\n     <td>\n      7/31.890\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      Go Shopping Kart\n     </td>\n    </tr>\n    <tr>\n     <td>\n      15\n     </td>\n     <td>\n      11\n     </td>\n     <td>\n      5:36.293\n     </td>\n     <td>\n      30.572\n     </td>\n     <td>\n      4/23.936\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      LIVFREE\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      16\n     </td>\n     <td>\n      9\n     </td>\n     <td>\n      3:28.135\n     </td>\n     <td>\n      23.126\n     </td>\n     <td>\n      2/18.296\n     </td>\n     <td>\n      9\n     </td>\n     <td>\n      Lightning McQueen\n     </td>\n    </tr>\n    <tr>\n     <td>\n      17\n     </td>\n     <td>\n      1\n     </td>\n     <td>\n      33.660\n     </td>\n     <td>\n      33.66\n     </td>\n     <td>\n      2/999.000\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      ITSABert\n     </td>\n    </tr>\n    <tr class="gtd">\n     <td>\n      18\n     </td>\n     <td>\n      1\n     </td>\n     <td>\n      7:23.381\n     </td>\n     <td>\n      443.381\n     </td>\n     <td>\n      4/999.000\n     </td>\n     <td>\n      0\n     </td>\n     <td>\n      The Chariot\n     </td>\n    </tr>\n   </tbody>\n  </table>\n  <br>\n   <table border="0" cellpadding="0" cellspacing="0" width="100%">\n    <tbody align="right">\n     <tr align="center" class="ttd">\n      <td align="center" colspan="9">\n       Lap Times\n      </td>\n     </tr>\n    </tbody>\n   </table>\n   <table border="0" cellpadding="0" cellspacing="0" width="100%">\n    <thead align="right" class="hth">\n     <tr class="hth">\n      <th>\n       Lap\n      </th>\n      <th>\n       Atomic Chibi\n      </th>\n      <th>\n       Lego Car\n      </th>\n      <th>\n       RU Greasy\n      </th>\n      <th>\n       The Bus\n      </th>\n      <th>\n       Amazon Box\n      </th>\n      <th>\n       Blue Meanie\n      </th>\n      <th>\n       Electric Koolaid Acid Test\n      </th>\n      <th>\n       MAV 721\n      </th>\n      <th>\n       Smoothie\n      </th>\n      <th>\n       Maximum Overdrive\n      </th>\n      <th>\n       FUBAR\n      </th>\n      <th>\n       Aerobot\n      </th>\n      <th>\n       Train Wrecks\n      </th>\n      <th>\n       Go Shopping Kart\n      </th>\n      <th>\n       LIVFREE\n      </th>\n      <th>\n       Lightning McQueen\n      </th>\n      <th>\n       ITSABert\n      </th>\n      <th>\n       The Chariot\n      </th>\n     </tr>\n    </thead>\n    <tbody align="right">\n     <tr class="gtd">\n      <th class="gth">\n       1\n      </th>\n      <td>\n       27.059\n      </td>\n      <td>\n       22.16\n      </td>\n      <td>\n       21.652\n      </td>\n      <td>\n       26.59\n      </td>\n      <td>\n       26.295\n      </td>\n      <td>\n       32.301\n      </td>\n      <td>\n       20.552\n      </td>\n      <td>\n       33.234\n      </td>\n      <td>\n       38.9\n      </td>\n      <td>\n       44.301\n      </td>\n      <td>\n       23.863\n      </td>\n      <td>\n       31.47\n      </td>\n      <td>\n       45.166\n      </td>\n      <td>\n       60.081\n      </td>\n      <td>\n       33.196\n      </td>\n      <td>\n       18.41\n      </td>\n      <td>\n       33.66\n      </td>\n      <td>\n       443.381\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       2\n      </th>\n      <td>\n       21.837\n      </td>\n      <td>\n       20.748\n      </td>\n      <td>\n       <span class="ibb">\n        <b>\n         19.707\n        </b>\n       </span>\n      </td>\n      <td>\n       22.777\n      </td>\n      <td>\n       24.287\n      </td>\n      <td>\n       26.41\n      </td>\n      <td>\n       19.641\n      </td>\n      <td>\n       29.696\n      </td>\n      <td>\n       31.84\n      </td>\n      <td>\n       48.96\n      </td>\n      <td>\n       188.376\n      </td>\n      <td>\n       26.789\n      </td>\n      <td>\n       143.93\n      </td>\n      <td>\n       53.864\n      </td>\n      <td>\n       26.715\n      </td>\n      <td>\n       <span class="ibb">\n        <b>\n         18.296\n        </b>\n       </span>\n      </td>\n     </tr>\n     <tr class="gtd">\n      <th class="gth">\n       3\n      </th>\n      <td>\n       23.4\n      </td>\n      <td>\n       23.64\n      </td>\n      <td>\n       24.138\n      </td>\n      <td>\n       23.777\n      </td>\n      <td>\n       24.204\n      </td>\n      <td>\n       39.404\n      </td>\n      <td>\n       24.439\n      </td>\n      <td>\n       38.047\n      </td>\n      <td>\n       34.861\n      </td>\n      <td>\n       36.4\n      </td>\n      <td>\n       29.956\n      </td>\n      <td>\n       38.925\n      </td>\n      <td>\n       34.686\n      </td>\n      <td>\n       70.535\n      </td>\n      <td>\n       40.347\n      </td>\n      <td>\n       22.275\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       4\n      </th>\n      <td>\n       36.008\n      </td>\n      <td>\n       36.209\n      </td>\n      <td>\n       36.685\n      </td>\n      <td>\n       36.757\n      </td>\n      <td>\n       36.476\n      </td>\n      <td>\n       26.461\n      </td>\n      <td>\n       37.13\n      </td>\n      <td>\n       26.52\n      </td>\n      <td>\n       32.308\n      </td>\n      <td>\n       35.228\n      </td>\n      <td>\n       23.683\n      </td>\n      <td>\n       26.436\n      </td>\n      <td>\n       31.459\n      </td>\n      <td>\n       53.898\n      </td>\n      <td>\n       <span class="ibb">\n        <b>\n         23.936\n        </b>\n       </span>\n      </td>\n      <td>\n       39.597\n      </td>\n     </tr>\n     <tr class="gtd">\n      <th class="gth">\n       5\n      </th>\n      <td>\n       19.711\n      </td>\n      <td>\n       22.152\n      </td>\n      <td>\n       22.088\n      </td>\n      <td>\n       22.356\n      </td>\n      <td>\n       22.602\n      </td>\n      <td>\n       26.849\n      </td>\n      <td>\n       21.907\n      </td>\n      <td>\n       28.426\n      </td>\n      <td>\n       31.814\n      </td>\n      <td>\n       32.73\n      </td>\n      <td>\n       23.037\n      </td>\n      <td>\n       33.389\n      </td>\n      <td>\n       37.995\n      </td>\n      <td>\n       56.866\n      </td>\n      <td>\n       30.591\n      </td>\n      <td>\n       23.212\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       6\n      </th>\n      <td>\n       25.947\n      </td>\n      <td>\n       27.522\n      </td>\n      <td>\n       24.974\n      </td>\n      <td>\n       25.304\n      </td>\n      <td>\n       24.695\n      </td>\n      <td>\n       24.627\n      </td>\n      <td>\n       24.131\n      </td>\n      <td>\n       27.661\n      </td>\n      <td>\n       31.869\n      </td>\n      <td>\n       36.5\n      </td>\n      <td>\n       21.913\n      </td>\n      <td>\n       26.834\n      </td>\n      <td>\n       28.373\n      </td>\n      <td>\n       35.433\n      </td>\n      <td>\n       31.868\n      </td>\n      <td>\n       18.959\n      </td>\n     </tr>\n     <tr class="gtd">\n      <th class="gth">\n       7\n      </th>\n      <td>\n       22.314\n      </td>\n      <td>\n       21.212\n      </td>\n      <td>\n       21.964\n      </td>\n      <td>\n       27.089\n      </td>\n      <td>\n       25.903\n      </td>\n      <td>\n       24.102\n      </td>\n      <td>\n       21.78\n      </td>\n      <td>\n       27.913\n      </td>\n      <td>\n       33.341\n      </td>\n      <td>\n       35.39\n      </td>\n      <td>\n       121.809\n      </td>\n      <td>\n       26.289\n      </td>\n      <td>\n       28.31\n      </td>\n      <td>\n       31.89\n      </td>\n      <td>\n       25.858\n      </td>\n      <td>\n       22.499\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       8\n      </th>\n      <td>\n       21.476\n      </td>\n      <td>\n       20.086\n      </td>\n      <td>\n       20.576\n      </td>\n      <td>\n       23.52\n      </td>\n      <td>\n       23.238\n      </td>\n      <td>\n       26.432\n      </td>\n      <td>\n       19.333\n      </td>\n      <td>\n       30.174\n      </td>\n      <td>\n       32.788\n      </td>\n      <td>\n       33.3\n      </td>\n      <td>\n       20.968\n      </td>\n      <td>\n       29.32\n      </td>\n      <td>\n       32.352\n      </td>\n      <td>\n       56.17\n      </td>\n      <td>\n       32.376\n      </td>\n      <td>\n       22.295\n      </td>\n     </tr>\n     <tr class="gtd">\n      <th class="gth">\n       9\n      </th>\n      <td>\n       25.126\n      </td>\n      <td>\n       22.243\n      </td>\n      <td>\n       20.9\n      </td>\n      <td>\n       28.273\n      </td>\n      <td>\n       28.464\n      </td>\n      <td>\n       25.27\n      </td>\n      <td>\n       21.994\n      </td>\n      <td>\n       29.451\n      </td>\n      <td>\n       32.208\n      </td>\n      <td>\n       36.235\n      </td>\n      <td>\n       22.678\n      </td>\n      <td>\n       <span class="ibb">\n        <b>\n         25.756\n        </b>\n       </span>\n      </td>\n      <td>\n       32.786\n      </td>\n      <td>\n       35.854\n      </td>\n      <td>\n       27.798\n      </td>\n      <td>\n       22.592\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       10\n      </th>\n      <td>\n       23.805\n      </td>\n      <td>\n       26.42\n      </td>\n      <td>\n       28.696\n      </td>\n      <td>\n       24.7\n      </td>\n      <td>\n       26.435\n      </td>\n      <td>\n       <span class="ibb">\n        <b>\n         22.462\n        </b>\n       </span>\n      </td>\n      <td>\n       28.161\n      </td>\n      <td>\n       29.63\n      </td>\n      <td>\n       31.72\n      </td>\n      <td>\n       32.57\n      </td>\n      <td>\n       21.317\n      </td>\n      <td>\n       25.877\n      </td>\n      <td>\n       28.783\n      </td>\n      <td>\n       41.807\n      </td>\n      <td>\n       29.437\n      </td>\n     </tr>\n     <tr class="gtd">\n      <th class="gth">\n       11\n      </th>\n      <td>\n       20.967\n      </td>\n      <td>\n       20.515\n      </td>\n      <td>\n       23.513\n      </td>\n      <td>\n       22.867\n      </td>\n      <td>\n       24.709\n      </td>\n      <td>\n       28.655\n      </td>\n      <td>\n       23.295\n      </td>\n      <td>\n       31.207\n      </td>\n      <td>\n       31.912\n      </td>\n      <td>\n       38.552\n      </td>\n      <td>\n       21.65\n      </td>\n      <td>\n       29.274\n      </td>\n      <td>\n       31.519\n      </td>\n      <td>\n       38.409\n      </td>\n      <td>\n       34.171\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       12\n      </th>\n      <td>\n       22.729\n      </td>\n      <td>\n       23.217\n      </td>\n      <td>\n       23.413\n      </td>\n      <td>\n       22.387\n      </td>\n      <td>\n       23.122\n      </td>\n      <td>\n       29.294\n      </td>\n      <td>\n       85.426\n      </td>\n      <td>\n       31.505\n      </td>\n      <td>\n       31.734\n      </td>\n      <td>\n       32.299\n      </td>\n      <td>\n       21.286\n      </td>\n      <td>\n       28.233\n      </td>\n      <td>\n       29.099\n      </td>\n      <td>\n       39.076\n      </td>\n     </tr>\n     <tr class="gtd">\n      <th class="gth">\n       13\n      </th>\n      <td>\n       20.559\n      </td>\n      <td>\n       22.995\n      </td>\n      <td>\n       22.441\n      </td>\n      <td>\n       24.142\n      </td>\n      <td>\n       25.398\n      </td>\n      <td>\n       23.309\n      </td>\n      <td>\n       22.099\n      </td>\n      <td>\n       43.533\n      </td>\n      <td>\n       32.113\n      </td>\n      <td>\n       <span class="ibb">\n        <b>\n         30.852\n        </b>\n       </span>\n      </td>\n      <td>\n       23.951\n      </td>\n      <td>\n       29.45\n      </td>\n      <td>\n       118.577\n      </td>\n      <td>\n       43.28\n      </td>\n     </tr>\n     <tr class="td">\n      <th class="th">\n       14\n      </th>\n      <td>\n       25.874\n      </td>\n      <td>\n       24.322\n      </td>\n      <td>\n       26.511\n      </td>\n      <td>\n       22.254\n      </td>\n      <td>\n       24.63\n      </td>\n      <td>\n 

In [3]:
print(soup.prettify())

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
   <meta content="Report generated by Flip Side Racing Software www.flipsideracing.org" name="description">
    <style type="text/css">
     p {

		  background-color: white;
		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  font-weight: normal;
		  padding-left: 1em;
		  padding-right: 1em;
		}
		td {

		  background-color: white;
		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  font-weight: normal;
		  padding-left: 1em;
		  padding-right: 1em;
		}
		th {

		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  padding-left: 1em;
		  padding-right: 1em;
		  background-color: white;
		  font-weight: normal;
		}
		.gtd td {

		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  padding-left: 1em;
		  padding-right: 1em;
		  background-color: #cccccc;
		  font-weight: normal;
		}
		.gth {

		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  padding-left: 1em;
		  padding-right: 1em;
		  background-color: #cccccc;
		  font-weight: normal;
		}
		.htd td {

		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  font-weight: bold;
		  padding-left: 1em;
		  padding-right: 1em;
		  background-color: #ffcc66;
		}
		.hth th {

		  color: black;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 12px;
		  font-weight: bold;
		  padding-left: 1em;
		  padding-right: 1em;
		  background-color: #ffcc66;
		}
		.ttd td {

		  background-color: white;
		  font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
		  font-size: 14px;
		  font-weight: bold;
		  letter-spacing: 2px;
		  padding-left: 1em;
		  padding-right: 1em;
		  color: red;
		}
		span.ibb {

		  background-color: #99ccff;
		}
    </style>
    <title>
     Race Results
    </title>
   </meta>
  </meta>
 </head>
 <body>
  <table border="0" cellpadding="0" cellspacing="0" width="100%">
   <tbody align="right">
    <tr>
     <td align="center" colspan="7">
      <img alt="Club logo" src="exampleLogo.jpg"/>
     </td>
    </tr>
    <tr class="ttd">
     <td align="center" colspan="7">
      Power Racing Series
     </td>
    </tr>
    <tr>
     <td align="center" colspan="7">
      2017 New York Sprint 2 Main 2017-09-23 15:07:22
     </td>
    </tr>
    <tr>
     <td align="center" colspan="7">
      Lap
     </td>
    </tr>
    <tr>
     <td align="center" colspan="7">
      Main
     </td>
    </tr>
    <tr>
     <td>
      <br>
      </br>
     </td>
    </tr>
   </tbody>
  </table>
  <table border="0" cellpadding="0" cellspacing="0" width="100%">
   <thead align="right" class="hth">
    <tr>
     <th>
      Position
     </th>
     <th>
      Laps
     </th>
     <th>
      Time
     </th>
     <th>
      Average
     </th>
     <th>
      Best
     </th>
     <th>
      Laps Leading
     </th>
     <th>
      Name
     </th>
    </tr>
   </thead>
   <tbody align="right">
    <tr>
     <td>
      1
     </td>
     <td>
      30
     </td>
     <td>
      11:20.014
     </td>
     <td>
      22.667
     </td>
     <td>
      30/19.501
     </td>
     <td>
      11
     </td>
     <td>
      Atomic Chibi
     </td>
    </tr>
    <tr class="gtd">
     <td>
      2
     </td>
     <td>
      30
     </td>
     <td>
      11:22.749
     </td>
     <td>
      22.758
     </td>
     <td>
      29/19.084
     </td>
     <td>
      8
     </td>
     <td>
      Lego Car
     </td>
    </tr>
    <tr>
     <td>
      3
     </td>
     <td>
      30
     </td>
     <td>
      11:36.034
     </td>
     <td>
      23.201
     </td>
     <td>
      2/19.707
     </td>
     <td>
      0
     </td>
     <td>
      RU Greasy
     </td>
    </tr>
    <tr class="gtd">
     <td>
      4
     </td>
     <td>
      28
     </td>
     <td>
      11:29.735
     </td>
     <td>
      24.633
     </td>
     <td>
      17/21.990
     </td>
     <td>
      0
     </td>
     <td>
      The Bus
     </td>
    </tr>
    <tr>
     <td>
      5
     </td>
     <td>
      28
     </td>
     <td>
      11:34.684
     </td>
     <td>
      24.81
     </td>
     <td>
      23/22.117
     </td>
     <td>
      0
     </td>
     <td>
      Amazon Box
     </td>
    </tr>
    <tr class="gtd">
     <td>
      6
     </td>
     <td>
      27
     </td>
     <td>
      11:36.440
     </td>
     <td>
      25.794
     </td>
     <td>
      10/22.462
     </td>
     <td>
      0
     </td>
     <td>
      Blue Meanie
     </td>
    </tr>
    <tr>
     <td>
      7
     </td>
     <td>
      27
     </td>
     <td>
      11:39.702
     </td>
     <td>
      25.915
     </td>
     <td>
      15/19.236
     </td>
     <td>
      2
     </td>
     <td>
      Electric Koolaid Acid Test
     </td>
    </tr>
    <tr class="gtd">
     <td>
      8
     </td>
     <td>
      22
     </td>
     <td>
      11:26.011
     </td>
     <td>
      31.182
     </td>
     <td>
      4/26.520
     </td>
     <td>
      0
     </td>
     <td>
      MAV 721
     </td>
    </tr>
    <tr>
     <td>
      9
     </td>
     <td>
      21
     </td>
     <td>
      11:35.918
     </td>
     <td>
      33.139
     </td>
     <td>
      14/31.678
     </td>
     <td>
      0
     </td>
     <td>
      Smoothie
     </td>
    </tr>
    <tr class="gtd">
     <td>
      10
     </td>
     <td>
      20
     </td>
     <td>
      11:43.065
     </td>
     <td>
      35.153
     </td>
     <td>
      13/30.852
     </td>
     <td>
      0
     </td>
     <td>
      Maximum Overdrive
     </td>
    </tr>
    <tr>
     <td>
      11
     </td>
     <td>
      19
     </td>
     <td>
      11:34.858
     </td>
     <td>
      36.571
     </td>
     <td>
      18/20.315
     </td>
     <td>
      0
     </td>
     <td>
      FUBAR
     </td>
    </tr>
    <tr class="gtd">
     <td>
      12
     </td>
     <td>
      16
     </td>
     <td>
      8:15.778
     </td>
     <td>
      30.986
     </td>
     <td>
      9/25.756
     </td>
     <td>
      0
     </td>
     <td>
      Aerobot
     </td>
    </tr>
    <tr>
     <td>
      13
     </td>
     <td>
      15
     </td>
     <td>
      11:36.035
     </td>
     <td>
      46.402
     </td>
     <td>
      7/28.310
     </td>
     <td>
      0
     </td>
     <td>
      Train Wrecks
     </td>
    </tr>
    <tr class="gtd">
     <td>
      14
     </td>
     <td>
      15
     </td>
     <td>
      11:40.800
     </td>
     <td>
      46.72
     </td>
     <td>
      7/31.890
     </td>
     <td>
      0
     </td>
     <td>
      Go Shopping Kart
     </td>
    </tr>
    <tr>
     <td>
      15
     </td>
     <td>
      11
     </td>
     <td>
      5:36.293
     </td>
     <td>
      30.572
     </td>
     <td>
      4/23.936
     </td>
     <td>
      0
     </td>
     <td>
      LIVFREE
     </td>
    </tr>
    <tr class="gtd">
     <td>
      16
     </td>
     <td>
      9
     </td>
     <td>
      3:28.135
     </td>
     <td>
      23.126
     </td>
     <td>
      2/18.296
     </td>
     <td>
      9
     </td>
     <td>
      Lightning McQueen
     </td>
    </tr>
    <tr>
     <td>
      17
     </td>
     <td>
      1
     </td>
     <td>
      33.660
     </td>
     <td>
      33.66
     </td>
     <td>
      2/999.000
     </td>
     <td>
      0
     </td>
     <td>
      ITSABert
     </td>
    </tr>
    <tr class="gtd">
     <td>
      18
     </td>
     <td>
      1
     </td>
     <td>
      7:23.381
     </td>
     <td>
      443.381
     </td>
     <td>
      4/999.000
     </td>
     <td>
      0
     </td>
     <td>
      The Chariot
     </td>
    </tr>
   </tbody>
  </table>
  <br>
   <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tbody align="right">
     <tr align="center" class="ttd">
      <td align="center" colspan="9">
       Lap Times
      </td>
     </tr>
    </tbody>
   </table>
   <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <thead align="right" class="hth">
     <tr class="hth">
      <th>
       Lap
      </th>
      <th>
       Atomic Chibi
      </th>
      <th>
       Lego Car
      </th>
      <th>
       RU Greasy
      </th>
      <th>
       The Bus
      </th>
      <th>
       Amazon Box
      </th>
      <th>
       Blue Meanie
      </th>
      <th>
       Electric Koolaid Acid Test
      </th>
      <th>
       MAV 721
      </th>
      <th>
       Smoothie
      </th>
      <th>
       Maximum Overdrive
      </th>
      <th>
       FUBAR
      </th>
      <th>
       Aerobot
      </th>
      <th>
       Train Wrecks
      </th>
      <th>
       Go Shopping Kart
      </th>
      <th>
       LIVFREE
      </th>
      <th>
       Lightning McQueen
      </th>
      <th>
       ITSABert
      </th>
      <th>
       The Chariot
      </th>
     </tr>
    </thead>
    <tbody align="right">
     <tr class="gtd">
      <th class="gth">
       1
      </th>
      <td>
       27.059
      </td>
      <td>
       22.16
      </td>
      <td>
       21.652
      </td>
      <td>
       26.59
      </td>
      <td>
       26.295
      </td>
      <td>
       32.301
      </td>
      <td>
       20.552
      </td>
      <td>
       33.234
      </td>
      <td>
       38.9
      </td>
      <td>
       44.301
      </td>
      <td>
       23.863
      </td>
      <td>
       31.47
      </td>
      <td>
       45.166
      </td>
      <td>
       60.081
      </td>
      <td>
       33.196
      </td>
      <td>
       18.41
      </td>
      <td>
       33.66
      </td>
      <td>
       443.381
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       2
      </th>
      <td>
       21.837
      </td>
      <td>
       20.748
      </td>
      <td>
       <span class="ibb">
        <b>
         19.707
        </b>
       </span>
      </td>
      <td>
       22.777
      </td>
      <td>
       24.287
      </td>
      <td>
       26.41
      </td>
      <td>
       19.641
      </td>
      <td>
       29.696
      </td>
      <td>
       31.84
      </td>
      <td>
       48.96
      </td>
      <td>
       188.376
      </td>
      <td>
       26.789
      </td>
      <td>
       143.93
      </td>
      <td>
       53.864
      </td>
      <td>
       26.715
      </td>
      <td>
       <span class="ibb">
        <b>
         18.296
        </b>
       </span>
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       3
      </th>
      <td>
       23.4
      </td>
      <td>
       23.64
      </td>
      <td>
       24.138
      </td>
      <td>
       23.777
      </td>
      <td>
       24.204
      </td>
      <td>
       39.404
      </td>
      <td>
       24.439
      </td>
      <td>
       38.047
      </td>
      <td>
       34.861
      </td>
      <td>
       36.4
      </td>
      <td>
       29.956
      </td>
      <td>
       38.925
      </td>
      <td>
       34.686
      </td>
      <td>
       70.535
      </td>
      <td>
       40.347
      </td>
      <td>
       22.275
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       4
      </th>
      <td>
       36.008
      </td>
      <td>
       36.209
      </td>
      <td>
       36.685
      </td>
      <td>
       36.757
      </td>
      <td>
       36.476
      </td>
      <td>
       26.461
      </td>
      <td>
       37.13
      </td>
      <td>
       26.52
      </td>
      <td>
       32.308
      </td>
      <td>
       35.228
      </td>
      <td>
       23.683
      </td>
      <td>
       26.436
      </td>
      <td>
       31.459
      </td>
      <td>
       53.898
      </td>
      <td>
       <span class="ibb">
        <b>
         23.936
        </b>
       </span>
      </td>
      <td>
       39.597
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       5
      </th>
      <td>
       19.711
      </td>
      <td>
       22.152
      </td>
      <td>
       22.088
      </td>
      <td>
       22.356
      </td>
      <td>
       22.602
      </td>
      <td>
       26.849
      </td>
      <td>
       21.907
      </td>
      <td>
       28.426
      </td>
      <td>
       31.814
      </td>
      <td>
       32.73
      </td>
      <td>
       23.037
      </td>
      <td>
       33.389
      </td>
      <td>
       37.995
      </td>
      <td>
       56.866
      </td>
      <td>
       30.591
      </td>
      <td>
       23.212
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       6
      </th>
      <td>
       25.947
      </td>
      <td>
       27.522
      </td>
      <td>
       24.974
      </td>
      <td>
       25.304
      </td>
      <td>
       24.695
      </td>
      <td>
       24.627
      </td>
      <td>
       24.131
      </td>
      <td>
       27.661
      </td>
      <td>
       31.869
      </td>
      <td>
       36.5
      </td>
      <td>
       21.913
      </td>
      <td>
       26.834
      </td>
      <td>
       28.373
      </td>
      <td>
       35.433
      </td>
      <td>
       31.868
      </td>
      <td>
       18.959
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       7
      </th>
      <td>
       22.314
      </td>
      <td>
       21.212
      </td>
      <td>
       21.964
      </td>
      <td>
       27.089
      </td>
      <td>
       25.903
      </td>
      <td>
       24.102
      </td>
      <td>
       21.78
      </td>
      <td>
       27.913
      </td>
      <td>
       33.341
      </td>
      <td>
       35.39
      </td>
      <td>
       121.809
      </td>
      <td>
       26.289
      </td>
      <td>
       28.31
      </td>
      <td>
       31.89
      </td>
      <td>
       25.858
      </td>
      <td>
       22.499
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       8
      </th>
      <td>
       21.476
      </td>
      <td>
       20.086
      </td>
      <td>
       20.576
      </td>
      <td>
       23.52
      </td>
      <td>
       23.238
      </td>
      <td>
       26.432
      </td>
      <td>
       19.333
      </td>
      <td>
       30.174
      </td>
      <td>
       32.788
      </td>
      <td>
       33.3
      </td>
      <td>
       20.968
      </td>
      <td>
       29.32
      </td>
      <td>
       32.352
      </td>
      <td>
       56.17
      </td>
      <td>
       32.376
      </td>
      <td>
       22.295
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       9
      </th>
      <td>
       25.126
      </td>
      <td>
       22.243
      </td>
      <td>
       20.9
      </td>
      <td>
       28.273
      </td>
      <td>
       28.464
      </td>
      <td>
       25.27
      </td>
      <td>
       21.994
      </td>
      <td>
       29.451
      </td>
      <td>
       32.208
      </td>
      <td>
       36.235
      </td>
      <td>
       22.678
      </td>
      <td>
       <span class="ibb">
        <b>
         25.756
        </b>
       </span>
      </td>
      <td>
       32.786
      </td>
      <td>
       35.854
      </td>
      <td>
       27.798
      </td>
      <td>
       22.592
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       10
      </th>
      <td>
       23.805
      </td>
      <td>
       26.42
      </td>
      <td>
       28.696
      </td>
      <td>
       24.7
      </td>
      <td>
       26.435
      </td>
      <td>
       <span class="ibb">
        <b>
         22.462
        </b>
       </span>
      </td>
      <td>
       28.161
      </td>
      <td>
       29.63
      </td>
      <td>
       31.72
      </td>
      <td>
       32.57
      </td>
      <td>
       21.317
      </td>
      <td>
       25.877
      </td>
      <td>
       28.783
      </td>
      <td>
       41.807
      </td>
      <td>
       29.437
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       11
      </th>
      <td>
       20.967
      </td>
      <td>
       20.515
      </td>
      <td>
       23.513
      </td>
      <td>
       22.867
      </td>
      <td>
       24.709
      </td>
      <td>
       28.655
      </td>
      <td>
       23.295
      </td>
      <td>
       31.207
      </td>
      <td>
       31.912
      </td>
      <td>
       38.552
      </td>
      <td>
       21.65
      </td>
      <td>
       29.274
      </td>
      <td>
       31.519
      </td>
      <td>
       38.409
      </td>
      <td>
       34.171
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       12
      </th>
      <td>
       22.729
      </td>
      <td>
       23.217
      </td>
      <td>
       23.413
      </td>
      <td>
       22.387
      </td>
      <td>
       23.122
      </td>
      <td>
       29.294
      </td>
      <td>
       85.426
      </td>
      <td>
       31.505
      </td>
      <td>
       31.734
      </td>
      <td>
       32.299
      </td>
      <td>
       21.286
      </td>
      <td>
       28.233
      </td>
      <td>
       29.099
      </td>
      <td>
       39.076
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       13
      </th>
      <td>
       20.559
      </td>
      <td>
       22.995
      </td>
      <td>
       22.441
      </td>
      <td>
       24.142
      </td>
      <td>
       25.398
      </td>
      <td>
       23.309
      </td>
      <td>
       22.099
      </td>
      <td>
       43.533
      </td>
      <td>
       32.113
      </td>
      <td>
       <span class="ibb">
        <b>
         30.852
        </b>
       </span>
      </td>
      <td>
       23.951
      </td>
      <td>
       29.45
      </td>
      <td>
       118.577
      </td>
      <td>
       43.28
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       14
      </th>
      <td>
       25.874
      </td>
      <td>
       24.322
      </td>
      <td>
       26.511
      </td>
      <td>
       22.254
      </td>
      <td>
       24.63
      </td>
      <td>
       22.95
      </td>
      <td>
       34.748
      </td>
      <td>
       29.42
      </td>
      <td>
       <span class="ibb">
        <b>
         31.678
        </b>
       </span>
      </td>
      <td>
       32.179
      </td>
      <td>
       21.559
      </td>
      <td>
       34.946
      </td>
      <td>
       36.489
      </td>
      <td>
       46.39
      </td>
     </tr>
     <tr class="gtd">
      <th class="gth">
       15
      </th>
      <td>
       23.106
      </td>
      <td>
       23.813
      </td>
      <td>
       23.373
      </td>
      <td>
       24.464
      </td>
      <td>
       23.864
      </td>
      <td>
       28.285
      </td>
      <td>
       <span class="ibb">
        <b>
         19.236
        </b>
       </span>
      </td>
      <td>
       29.18
      </td>
      <td>
       32.052
      </td>
      <td>
       33.347
      </td>
      <td>
       23.6
      </td>
      <td>
       38.047
      </td>
      <td>
       36.511
      </td>
      <td>
       37.247
      </td>
     </tr>
     <tr class="td">
      <th class="th">
       16
      </th>
      <td>
       22.986
      </td>
      <td>
       21.304
      </td>
      <td>
       24.049
      </td>
      <td>
       27.205
      </td>
      <td>
       27.725
      </td>
      <td>
       23.381
      </td>
      <td>
       19.934
      </td>
      <td>
       30.992
      </td>
      <td>
       32.078
      </td>
      <td>
       33.297
      </td>
      <td>
       21.1
      </td>
      <td>
       44.743
      </td>
     </tr>

In [4]:
soup.title

In [5]:
soup.title.name

'title'

In [6]:
soup.title.string

'Race Results'

In [7]:
soup.title.parent.name

'meta'

In [8]:
soup.a

In [9]:
soup.table

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tbody align="right">
<tr>
<td align="center" colspan="7"><img alt="Club logo" src="exampleLogo.jpg"/></td>
</tr>
<tr class="ttd">
<td align="center" colspan="7">Power Racing Series</td>
</tr>
<tr>
<td align="center" colspan="7">2017 New York Sprint 2 Main 2017-09-23 15:07:22</td>
</tr>
<tr>
<td align="center" colspan="7">Lap</td>
</tr>
<tr>
<td align="center" colspan="7">Main</td>
</tr>
<tr>
<td>
<br>
</br></td>
</tr>
</tbody>
</table>

In [10]:
soup.find_all('table')

[<table border="0" cellpadding="0" cellspacing="0" width="100%">
 <tbody align="right">
 <tr>
 <td align="center" colspan="7"><img alt="Club logo" src="exampleLogo.jpg"/></td>
 </tr>
 <tr class="ttd">
 <td align="center" colspan="7">Power Racing Series</td>
 </tr>
 <tr>
 <td align="center" colspan="7">2017 New York Sprint 2 Main 2017-09-23 15:07:22</td>
 </tr>
 <tr>
 <td align="center" colspan="7">Lap</td>
 </tr>
 <tr>
 <td align="center" colspan="7">Main</td>
 </tr>
 <tr>
 <td>
 <br>
 </br></td>
 </tr>
 </tbody>
 </table>, <table border="0" cellpadding="0" cellspacing="0" width="100%">
 <thead align="right" class="hth">
 <tr>
 <th>Position</th>
 <th>Laps</th>
 <th>Time</th>
 <th>Average</th>
 <th>Best</th>
 <th>Laps Leading</th>
 <th>Name</th>
 </tr>
 </thead>
 <tbody align="right">
 <tr>
 <td>1</td>
 <td>30</td>
 <td>11:20.014</td>
 <td>22.667</td>
 <td>30/19.501</td>
 <td>11</td>
 <td>Atomic Chibi</td>
 </tr>
 <tr class="gtd">
 <td>2</td>
 <td>30</td>
 <td>11:22.749</td>
 <td>22.758</td>
 <td>29/19.084</td>
 <td>8</td>
 <td>Lego Car</td>
 </tr>
 <tr>
 <td>3</td>
 <td>30</td>
 <td>11:36.034</td>
 <td>23.201</td>
 <td>2/19.707</td>
 <td>0</td>
 <td>RU Greasy</td>
 </tr>
 <tr class="gtd">
 <td>4</td>
 <td>28</td>
 <td>11:29.735</td>
 <td>24.633</td>
 <td>17/21.990</td>
 <td>0</td>
 <td>The Bus</td>
 </tr>
 <tr>
 <td>5</td>
 <td>28</td>
 <td>11:34.684</td>
 <td>24.81</td>
 <td>23/22.117</td>
 <td>0</td>
 <td>Amazon Box</td>
 </tr>
 <tr class="gtd">
 <td>6</td>
 <td>27</td>
 <td>11:36.440</td>
 <td>25.794</td>
 <td>10/22.462</td>
 <td>0</td>
 <td>Blue Meanie</td>
 </tr>
 <tr>
 <td>7</td>
 <td>27</td>
 <td>11:39.702</td>
 <td>25.915</td>
 <td>15/19.236</td>
 <td>2</td>
 <td>Electric Koolaid Acid Test</td>
 </tr>
 <tr class="gtd">
 <td>8</td>
 <td>22</td>
 <td>11:26.011</td>
 <td>31.182</td>
 <td>4/26.520</td>
 <td>0</td>
 <td>MAV 721</td>
 </tr>
 <tr>
 <td>9</td>
 <td>21</td>
 <td>11:35.918</td>
 <td>33.139</td>
 <td>14/31.678</td>
 <td>0</td>
 <td>Smoothie</td>
 </tr>
 <tr class="gtd">
 <td>10</td>
 <td>20</td>
 <td>11:43.065</td>
 <td>35.153</td>
 <td>13/30.852</td>
 <td>0</td>
 <td>Maximum Overdrive</td>
 </tr>
 <tr>
 <td>11</td>
 <td>19</td>
 <td>11:34.858</td>
 <td>36.571</td>
 <td>18/20.315</td>
 <td>0</td>
 <td>FUBAR</td>
 </tr>
 <tr class="gtd">
 <td>12</td>
 <td>16</td>
 <td>8:15.778</td>
 <td>30.986</td>
 <td>9/25.756</td>
 <td>0</td>
 <td>Aerobot</td>
 </tr>
 <tr>
 <td>13</td>
 <td>15</td>
 <td>11:36.035</td>
 <td>46.402</td>
 <td>7/28.310</td>
 <td>0</td>
 <td>Train Wrecks</td>
 </tr>
 <tr class="gtd">
 <td>14</td>
 <td>15</td>
 <td>11:40.800</td>
 <td>46.72</td>
 <td>7/31.890</td>
 <td>0</td>
 <td>Go Shopping Kart</td>
 </tr>
 <tr>
 <td>15</td>
 <td>11</td>
 <td>5:36.293</td>
 <td>30.572</td>
 <td>4/23.936</td>
 <td>0</td>
 <td>LIVFREE</td>
 </tr>
 <tr class="gtd">
 <td>16</td>
 <td>9</td>
 <td>3:28.135</td>
 <td>23.126</td>
 <td>2/18.296</td>
 <td>9</td>
 <td>Lightning McQueen</td>
 </tr>
 <tr>
 <td>17</td>
 <td>1</td>
 <td>33.660</td>
 <td>33.66</td>
 <td>2/999.000</td>
 <td>0</td>
 <td>ITSABert</td>
 </tr>
 <tr class="gtd">
 <td>18</td>
 <td>1</td>
 <td>7:23.381</td>
 <td>443.381</td>
 <td>4/999.000</td>
 <td>0</td>
 <td>The Chariot</td>
 </tr>
 </tbody>
 </table>, <table border="0" cellpadding="0" cellspacing="0" width="100%">
 <tbody align="right">
 <tr align="center" class="ttd">
 <td align="center" colspan="9">Lap Times</td>
 </tr>
 </tbody>
 </table>, <table border="0" cellpadding="0" cellspacing="0" width="100%">
 <thead align="right" class="hth">
 <tr class="hth">
 <th>Lap</th>
 <th>Atomic Chibi</th>
 <th>Lego Car</th>
 <th>RU Greasy</th>
 <th>The Bus</th>
 <th>Amazon Box</th>
 <th>Blue Meanie</th>
 <th>Electric Koolaid Acid Test</th>
 <th>MAV 721</th>
 <th>Smoothie</th>
 <th>Maximum Overdrive</th>
 <th>FUBAR</th>
 <th>Aerobot</th>
 <th>Train Wrecks</th>
 <th>Go Shopping Kart</th>
 <th>LIVFREE</th>
 <th>Lightning McQueen</th>
 <th>ITSABert</th>
 <th>The Chariot</th>
 </tr>
 </thead>
 <tbody align="right">
 <tr class="gtd">
 <th class="gth">1</th>
 <td>27.059</td>
 <td>22.16</td>
 <td>21.652</td>
 <td>26.59</td>
 <td>26.295</td>
 <td>32.301</td>
 <td>20.552</td>
 <td>33.234</td>
 <td>38.9</td>
 <td>44.301</td>
 <td>23.863</td>
 <td>31.47</td>
 <td>45.166</td>
 <td>60.081</td>
 <td>33.196</td>
 <td>18.41</td>
 <td>33.66</td>
 <td>443.381</td>
 </tr>
 <tr class="td">
 <th class="th">2</th>
 <td>21.837</td>
 <td>20.748</td>
 <td><span class="ibb">
 <b>19.707</b>
 </span>
 </td>
 <td>22.777</td>
 <td>24.287</td>
 <td>26.41</td>
 <td>19.641</td>
 <td>29.696</td>
 <td>31.84</td>
 <td>48.96</td>
 <td>188.376</td>
 <td>26.789</td>
 <td>143.93</td>
 <td>53.864</td>
 <td>26.715</td>
 <td><span class="ibb">
 <b>18.296</b>
 </span>
 </td>
 </tr>
 <tr class="gtd">
 <th class="gth">3</th>
 <td>23.4</td>
 <td>23.64</td>
 <td>24.138</td>
 <td>23.777</td>
 <td>24.204</td>
 <td>39.404</td>
 <td>24.439</td>
 <td>38.047</td>
 <td>34.861</td>
 <td>36.4</td>
 <td>29.956</td>
 <td>38.925</td>
 <td>34.686</td>
 <td>70.535</td>
 <td>40.347</td>
 <td>22.275</td>
 </tr>
 <tr class="td">
 <th class="th">4</th>
 <td>36.008</td>
 <td>36.209</td>
 <td>36.685</td>
 <td>36.757</td>
 <td>36.476</td>
 <td>26.461</td>
 <td>37.13</td>
 <td>26.52</td>
 <td>32.308</td>
 <td>35.228</td>
 <td>23.683</td>
 <td>26.436</td>
 <td>31.459</td>
 <td>53.898</td>
 <td><span class="ibb">
 <b>23.936</b>
 </span>
 </td>
 <td>39.597</td>
 </tr>
 <tr class="gtd">
 <th class="gth">5</th>
 <td>19.711</td>
 <td>22.152</td>
 <td>22.088</td>
 <td>22.356</td>
 <td>22.602</td>
 <td>26.849</td>
 <td>21.907</td>
 <td>28.426</td>
 <td>31.814</td>
 <td>32.73</td>
 <td>23.037</td>
 <td>33.389</td>
 <td>37.995</td>
 <td>56.866</td>
 <td>30.591</td>
 <td>23.212</td>
 </tr>
 <tr class="td">
 <th class="th">6</th>
 <td>25.947</td>
 <td>27.522</td>
 <td>24.974</td>
 <td>25.304</td>
 <td>24.695</td>
 <td>24.627</td>
 <td>24.131</td>
 <td>27.661</td>
 <td>31.869</td>
 <td>36.5</td>
 <td>21.913</td>
 <td>26.834</td>
 <td>28.373</td>
 <td>35.433</td>
 <td>31.868</td>
 <td>18.959</td>
 </tr>
 <tr class="gtd">
 <th class="gth">7</th>
 <td>22.314</td>
 <td>21.212</td>
 <td>21.964</td>
 <td>27.089</td>
 <td>25.903</td>
 <td>24.102</td>
 <td>21.78</td>
 <td>27.913</td>
 <td>33.341</td>
 <td>35.39</td>
 <td>121.809</td>
 <td>26.289</td>
 <td>28.31</td>
 <td>31.89</td>
 <td>25.858</td>
 <td>22.499</td>
 </tr>
 <tr class="td">
 <th class="th">8</th>
 <td>21.476</td>
 <td>20.086</td>
 <td>20.576</td>
 <td>23.52</td>
 <td>23.238</td>
 <td>26.432</td>
 <td>19.333</td>
 <td>30.174</td>
 <td>32.788</td>
 <td>33.3</td>
 <td>20.968</td>
 <td>29.32</td>
 <td>32.352</td>
 <td>56.17</td>
 <td>32.376</td>
 <td>22.295</td>
 </tr>
 <tr class="gtd">
 <th class="gth">9</th>
 <td>25.126</td>
 <td>22.243</td>
 <td>20.9</td>
 <td>28.273</td>
 <td>28.464</td>
 <td>25.27</td>
 <td>21.994</td>
 <td>29.451</td>
 <td>32.208</td>
 <td>36.235</td>
 <td>22.678</td>
 <td><span class="ibb">
 <b>25.756</b>
 </span>
 </td>
 <td>32.786</td>
 <td>35.854</td>
 <td>27.798</td>
 <td>22.592</td>
 </tr>
 <tr class="td">
 <th class="th">10</th>
 <td>23.805</td>
 <td>26.42</td>
 <td>28.696</td>
 <td>24.7</td>
 <td>26.435</td>
 <td><span class="ibb">
 <b>22.462</b>
 </span>
 </td>
 <td>28.161</td>
 <td>29.63</td>
 <td>31.72</td>
 <td>32.57</td>
 <td>21.317</td>
 <td>25.877</td>
 <td>28.783</td>
 <td>41.807</td>
 <td>29.437</td>
 </tr>
 <tr class="gtd">
 <th class="gth">11</th>
 <td>20.967</td>
 <td>20.515</td>
 <td>23.513</td>
 <td>22.867</td>
 <td>24.709</td>
 <td>28.655</td>
 <td>23.295</td>
 <td>31.207</td>
 <td>31.912</td>
 <td>38.552</td>
 <td>21.65</td>
 <td>29.274</td>
 <td>31.519</td>
 <td>38.409</td>
 <td>34.171</td>
 </tr>
 <tr class="td">
 <th class="th">12</th>
 <td>22.729</td>
 <td>23.217</td>
 <td>23.413</td>
 <td>22.387</td>
 <td>23.122</td>
 <td>29.294</td>
 <td>85.426</td>
 <td>31.505</td>
 <td>31.734</td>
 <td>32.299</td>
 <td>21.286</td>
 <td>28.233</td>
 <td>29.099</td>
 <td>39.076</td>
 </tr>
 <tr class="gtd">
 <th class="gth">13</th>
 <td>20.559</td>
 <td>22.995</td>
 <td>22.441</td>
 <td>24.142</td>
 <td>25.398</td>
 <td>23.309</td>
 <td>22.099</td>
 <td>43.533</td>
 <td>32.113</td>
 <td><span class="ibb">
 <b>30.852</b>
 </span>
 </td>
 <td>23.951</td>
 <td>29.45</td>
 <td>118.577</td>
 <td>43.28</td>
 </tr>
 <tr class="td">
 <th class="th">14</th>
 <td>25.874</td>
 <td>24.322</td>
 <td>26.511</td>
 <td>22.254</td>
 <td>24.63</td>
 <td>22.95</td>
 <td>34.748</td>
 <td>29.42</td>
 <td><span class="ibb">
 <b>31.678</b>
 </span>
 </td>
 <td>32.179</td>
 <td>21.559</td>
 <td>34.946</td>
 <td>36.489</td>
 <td>46.39</td>
 </tr>
 <tr class="gtd">
 <th class="gth">15</th>
 <td>23.106</td>
 <td>23.813</td>
 <td>23.373</td>
 <td>24.464</td>
 <td>23.864</td>
 <td>28.285</td>
 <td><span class="ibb">
 <b>19.236</b>
 </span>
 </td>
 <td>29.18</td>
 <td>32.052</td>
 <td>33.347</td>
 <td>23.6</td>
 <td>38.047</td>
 <td>36.511</td>
 <td>37.247</td>
 </tr>
 <tr class="td">
 <th class="th">16</th>
 <td>22.986</td>
 <td>21.304</td>
 <td>24.049</td>
 <td>27.205</td>
 <td>27.725</td>
 <td>23.381</td>
 <td>19.934</td>
 <td>30.992</td>
 <td>32.078</td>
 <td>33.297</td>
 <td>21.1</td>
 <td>44.743</td>
 </tr>
 <tr class="gtd">
 <th class="gth">17</th>
 <td>25.367</td>
 <td>28.265</td>
 <td>26.946</td>
 <td>21.99</td>
 <td>24.158</td>
 <td>23.059</td>
 <td>20.756</td>
 <td>31.912</td>
 <td>34.114</td>
 <td>33.643</td>
 <td>23.071</td>
 </tr>
 <tr class="td">
 <th class="th">18</th>
 <td>20.274</td>
 <td>21.281</td>
 <td>21.608</td>
 <td>22.263</td>
 <td>22.756</td>
 <td>23.366</td>
 <td>27.03</td>
 <td>30.686</td>
 <td>33.796</td>
 <td>32.415</td>
 <td><span class="ibb">
 <b>20.315</b>
 </span>
 </td>
 </tr>
 <tr class="gtd">
 <th class="gth">19</th>
 <td>20.742</td>
 <td>20.4</td>
 <td>21.016</td>
 <td>24.632</td>
 <td>25.887</td>
 <td>24.817</td>
 <td>19.903</td>
 <td>32.966</td>
 <td>34.037</td>
 <td>31.031</td>
 <td>20.726</td>
 </tr>
 <tr class="td">
 <th class="th">20</th>
 <td>22.476</td>
 <td>23.602</td>
 <td>22.57</td>
 <td>22.737</td>
 <td>22.388</td>
 <td>24.941</td>
 <td>22.271</td>
 <td>31.102</td>
 <td>36.092</td>
 <td>33.836</td>
 </tr>
 <tr class="gtd">
 <th class="gth">21</th>
 <td>20.151</td>
 <td>20.238</td>
 <td>21.527</td>
 <td>22.959</td>
 <td>24.326</td>
 <td>23.376</td>
 <td>22.416</td>
 <td>32.901</td>
 <td>34.663</td>
 </tr>
 <tr class="td">
 <th class="th">22</th>
 <td>20.308</td>
 <td>20.34</td>
 <td>21.392</td>
 <td>23.267</td>
 <td>23.185</td>
 <td>24.041</td>
 <td>21.301</td>
 <td>29.855</td>
 </tr>
 <tr class="gtd">
 <th class="gth">23</th>
 <td>20.809</td>
 <td>21.393</td>
 <td>21.214</td>
 <td>23.041</td>
 <td><span class="ibb">
 <b>22.117</b>
 </span>
 </td>
 <td>25.367</td>
 <td>24.283</td>
 </tr>
 <tr class="td">
 <th class="th">24</th>
 <td>21.77</td>
 <td>22.758</td>
 <td>21.981</td>
 <td>31.424</td>
 <td>23.318</td>
 <td>23.913</td>
 <td>22.688</td>
 </tr>
 <tr class="gtd">
 <th class="gth">25</th>
 <td>20.35</td>
 <td>21.098</td>
 <td>24.057</td>
 <td>23.377</td>
 <td>23.484</td>
 <td>23.518</td>
 <td>28.425</td>
 </tr>
 <tr class="td">
 <th class="th">26</th>
 <td>23.987</td>
 <td>22.24</td>
 <td>23.203</td>
 <td>22.857</td>
 <td>23.812</td>
 <td>23.443</td>
 <td>19.956</td>
 </tr>
 <tr class="gtd">
 <th class="gth">27</th>
 <td>21.193</td>
 <td>23.591</td>
 <td>21.028</td>
 <td>23.092</td>
 <td>23.133</td>
 <td>26.407</td>
 <td>26.867</td>
 </tr>
 <tr class="td">
 <th class="th">28</th>
 <td>19.777</td>
 <td>20.598</td>
 <td>24.015</td>
 <td>23.634</td>
 <td>24.073</td>
 </tr>
 <tr class="gtd">
 <th class="gth">29</th>
 <td>20.405</td>
 <td><span class="ibb">
 <b>19.084</b>
 </span>
 </td>
 <td>20.059</td>
 </tr>
 <tr class="td">
 <th class="th">30</th>
 <td><span class="ibb">
 <b>19.501</b>
 </span>
 </td>
 <td>19.303</td>
 <td>20.738</td>
 </tr>
 </tbody>
 </table>]

In [11]:
for table in soup.find_all('table'):
    print(table)

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tbody align="right">
<tr>
<td align="center" colspan="7"><img alt="Club logo" src="exampleLogo.jpg"/></td>
</tr>
<tr class="ttd">
<td align="center" colspan="7">Power Racing Series</td>
</tr>
<tr>
<td align="center" colspan="7">2017 New York Sprint 2 Main 2017-09-23 15:07:22</td>
</tr>
<tr>
<td align="center" colspan="7">Lap</td>
</tr>
<tr>
<td align="center" colspan="7">Main</td>
</tr>
<tr>
<td>
<br>
</br></td>
</tr>
</tbody>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<thead align="right" class="hth">
<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>
</thead>
<tbody align="right">
<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>
<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>
<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>
<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>
<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>
<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>
<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>
<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>
<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>
<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>
<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>
<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>
<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>
<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>
<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>
<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>
<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>
<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>
</tbody>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tbody align="right">
<tr align="center" class="ttd">
<td align="center" colspan="9">Lap Times</td>
</tr>
</tbody>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<thead align="right" class="hth">
<tr class="hth">
<th>Lap</th>
<th>Atomic Chibi</th>
<th>Lego Car</th>
<th>RU Greasy</th>
<th>The Bus</th>
<th>Amazon Box</th>
<th>Blue Meanie</th>
<th>Electric Koolaid Acid Test</th>
<th>MAV 721</th>
<th>Smoothie</th>
<th>Maximum Overdrive</th>
<th>FUBAR</th>
<th>Aerobot</th>
<th>Train Wrecks</th>
<th>Go Shopping Kart</th>
<th>LIVFREE</th>
<th>Lightning McQueen</th>
<th>ITSABert</th>
<th>The Chariot</th>
</tr>
</thead>
<tbody align="right">
<tr class="gtd">
<th class="gth">1</th>
<td>27.059</td>
<td>22.16</td>
<td>21.652</td>
<td>26.59</td>
<td>26.295</td>
<td>32.301</td>
<td>20.552</td>
<td>33.234</td>
<td>38.9</td>
<td>44.301</td>
<td>23.863</td>
<td>31.47</td>
<td>45.166</td>
<td>60.081</td>
<td>33.196</td>
<td>18.41</td>
<td>33.66</td>
<td>443.381</td>
</tr>
<tr class="td">
<th class="th">2</th>
<td>21.837</td>
<td>20.748</td>
<td><span class="ibb">
<b>19.707</b>
</span>
</td>
<td>22.777</td>
<td>24.287</td>
<td>26.41</td>
<td>19.641</td>
<td>29.696</td>
<td>31.84</td>
<td>48.96</td>
<td>188.376</td>
<td>26.789</td>
<td>143.93</td>
<td>53.864</td>
<td>26.715</td>
<td><span class="ibb">
<b>18.296</b>
</span>
</td>
</tr>
<tr class="gtd">
<th class="gth">3</th>
<td>23.4</td>
<td>23.64</td>
<td>24.138</td>
<td>23.777</td>
<td>24.204</td>
<td>39.404</td>
<td>24.439</td>
<td>38.047</td>
<td>34.861</td>
<td>36.4</td>
<td>29.956</td>
<td>38.925</td>
<td>34.686</td>
<td>70.535</td>
<td>40.347</td>
<td>22.275</td>
</tr>
<tr class="td">
<th class="th">4</th>
<td>36.008</td>
<td>36.209</td>
<td>36.685</td>
<td>36.757</td>
<td>36.476</td>
<td>26.461</td>
<td>37.13</td>
<td>26.52</td>
<td>32.308</td>
<td>35.228</td>
<td>23.683</td>
<td>26.436</td>
<td>31.459</td>
<td>53.898</td>
<td><span class="ibb">
<b>23.936</b>
</span>
</td>
<td>39.597</td>
</tr>
<tr class="gtd">
<th class="gth">5</th>
<td>19.711</td>
<td>22.152</td>
<td>22.088</td>
<td>22.356</td>
<td>22.602</td>
<td>26.849</td>
<td>21.907</td>
<td>28.426</td>
<td>31.814</td>
<td>32.73</td>
<td>23.037</td>
<td>33.389</td>
<td>37.995</td>
<td>56.866</td>
<td>30.591</td>
<td>23.212</td>
</tr>
<tr class="td">
<th class="th">6</th>
<td>25.947</td>
<td>27.522</td>
<td>24.974</td>
<td>25.304</td>
<td>24.695</td>
<td>24.627</td>
<td>24.131</td>
<td>27.661</td>
<td>31.869</td>
<td>36.5</td>
<td>21.913</td>
<td>26.834</td>
<td>28.373</td>
<td>35.433</td>
<td>31.868</td>
<td>18.959</td>
</tr>
<tr class="gtd">
<th class="gth">7</th>
<td>22.314</td>
<td>21.212</td>
<td>21.964</td>
<td>27.089</td>
<td>25.903</td>
<td>24.102</td>
<td>21.78</td>
<td>27.913</td>
<td>33.341</td>
<td>35.39</td>
<td>121.809</td>
<td>26.289</td>
<td>28.31</td>
<td>31.89</td>
<td>25.858</td>
<td>22.499</td>
</tr>
<tr class="td">
<th class="th">8</th>
<td>21.476</td>
<td>20.086</td>
<td>20.576</td>
<td>23.52</td>
<td>23.238</td>
<td>26.432</td>
<td>19.333</td>
<td>30.174</td>
<td>32.788</td>
<td>33.3</td>
<td>20.968</td>
<td>29.32</td>
<td>32.352</td>
<td>56.17</td>
<td>32.376</td>
<td>22.295</td>
</tr>
<tr class="gtd">
<th class="gth">9</th>
<td>25.126</td>
<td>22.243</td>
<td>20.9</td>
<td>28.273</td>
<td>28.464</td>
<td>25.27</td>
<td>21.994</td>
<td>29.451</td>
<td>32.208</td>
<td>36.235</td>
<td>22.678</td>
<td><span class="ibb">
<b>25.756</b>
</span>
</td>
<td>32.786</td>
<td>35.854</td>
<td>27.798</td>
<td>22.592</td>
</tr>
<tr class="td">
<th class="th">10</th>
<td>23.805</td>
<td>26.42</td>
<td>28.696</td>
<td>24.7</td>
<td>26.435</td>
<td><span class="ibb">
<b>22.462</b>
</span>
</td>
<td>28.161</td>
<td>29.63</td>
<td>31.72</td>
<td>32.57</td>
<td>21.317</td>
<td>25.877</td>
<td>28.783</td>
<td>41.807</td>
<td>29.437</td>
</tr>
<tr class="gtd">
<th class="gth">11</th>
<td>20.967</td>
<td>20.515</td>
<td>23.513</td>
<td>22.867</td>
<td>24.709</td>
<td>28.655</td>
<td>23.295</td>
<td>31.207</td>
<td>31.912</td>
<td>38.552</td>
<td>21.65</td>
<td>29.274</td>
<td>31.519</td>
<td>38.409</td>
<td>34.171</td>
</tr>
<tr class="td">
<th class="th">12</th>
<td>22.729</td>
<td>23.217</td>
<td>23.413</td>
<td>22.387</td>
<td>23.122</td>
<td>29.294</td>
<td>85.426</td>
<td>31.505</td>
<td>31.734</td>
<td>32.299</td>
<td>21.286</td>
<td>28.233</td>
<td>29.099</td>
<td>39.076</td>
</tr>
<tr class="gtd">
<th class="gth">13</th>
<td>20.559</td>
<td>22.995</td>
<td>22.441</td>
<td>24.142</td>
<td>25.398</td>
<td>23.309</td>
<td>22.099</td>
<td>43.533</td>
<td>32.113</td>
<td><span class="ibb">
<b>30.852</b>
</span>
</td>
<td>23.951</td>
<td>29.45</td>
<td>118.577</td>
<td>43.28</td>
</tr>
<tr class="td">
<th class="th">14</th>
<td>25.874</td>
<td>24.322</td>
<td>26.511</td>
<td>22.254</td>
<td>24.63</td>
<td>22.95</td>
<td>34.748</td>
<td>29.42</td>
<td><span class="ibb">
<b>31.678</b>
</span>
</td>
<td>32.179</td>
<td>21.559</td>
<td>34.946</td>
<td>36.489</td>
<td>46.39</td>
</tr>
<tr class="gtd">
<th class="gth">15</th>
<td>23.106</td>
<td>23.813</td>
<td>23.373</td>
<td>24.464</td>
<td>23.864</td>
<td>28.285</td>
<td><span class="ibb">
<b>19.236</b>
</span>
</td>
<td>29.18</td>
<td>32.052</td>
<td>33.347</td>
<td>23.6</td>
<td>38.047</td>
<td>36.511</td>
<td>37.247</td>
</tr>
<tr class="td">
<th class="th">16</th>
<td>22.986</td>
<td>21.304</td>
<td>24.049</td>
<td>27.205</td>
<td>27.725</td>
<td>23.381</td>
<td>19.934</td>
<td>30.992</td>
<td>32.078</td>
<td>33.297</td>
<td>21.1</td>
<td>44.743</td>
</tr>
<tr class="gtd">
<th class="gth">17</th>
<td>25.367</td>
<td>28.265</td>
<td>26.946</td>
<td>21.99</td>
<td>24.158</td>
<td>23.059</td>
<td>20.756</td>
<td>31.912</td>
<td>34.114</td>
<td>33.643</td>
<td>23.071</td>
</tr>
<tr class="td">
<th class="th">18</th>
<td>20.274</td>
<td>21.281</td>
<td>21.608</td>
<td>22.263</td>
<td>22.756</td>
<td>23.366</td>
<td>27.03</td>
<td>30.686</td>
<td>33.796</td>
<td>32.415</td>
<td><span class="ibb">
<b>20.315</b>
</span>
</td>
</tr>
<tr class="gtd">
<th class="gth">19</th>
<td>20.742</td>
<td>20.4</td>
<td>21.016</td>
<td>24.632</td>
<td>25.887</td>
<td>24.817</td>
<td>19.903</td>
<td>32.966</td>
<td>34.037</td>
<td>31.031</td>
<td>20.726</td>
</tr>
<tr class="td">
<th class="th">20</th>
<td>22.476</td>
<td>23.602</td>
<td>22.57</td>
<td>22.737</td>
<td>22.388</td>
<td>24.941</td>
<td>22.271</td>
<td>31.102</td>
<td>36.092</td>
<td>33.836</td>
</tr>
<tr class="gtd">
<th class="gth">21</th>
<td>20.151</td>
<td>20.238</td>
<td>21.527</td>
<td>22.959</td>
<td>24.326</td>
<td>23.376</td>
<td>22.416</td>
<td>32.901</td>
<td>34.663</td>
</tr>
<tr class="td">
<th class="th">22</th>
<td>20.308</td>
<td>20.34</td>
<td>21.392</td>
<td>23.267</td>
<td>23.185</td>
<td>24.041</td>
<td>21.301</td>
<td>29.855</td>
</tr>
<tr class="gtd">
<th class="gth">23</th>
<td>20.809</td>
<td>21.393</td>
<td>21.214</td>
<td>23.041</td>
<td><span class="ibb">
<b>22.117</b>
</span>
</td>
<td>25.367</td>
<td>24.283</td>
</tr>
<tr class="td">
<th class="th">24</th>
<td>21.77</td>
<td>22.758</td>
<td>21.981</td>
<td>31.424</td>
<td>23.318</td>
<td>23.913</td>
<td>22.688</td>
</tr>
<tr class="gtd">
<th class="gth">25</th>
<td>20.35</td>
<td>21.098</td>
<td>24.057</td>
<td>23.377</td>
<td>23.484</td>
<td>23.518</td>
<td>28.425</td>
</tr>
<tr class="td">
<th class="th">26</th>
<td>23.987</td>
<td>22.24</td>
<td>23.203</td>
<td>22.857</td>
<td>23.812</td>
<td>23.443</td>
<td>19.956</td>
</tr>
<tr class="gtd">
<th class="gth">27</th>
<td>21.193</td>
<td>23.591</td>
<td>21.028</td>
<td>23.092</td>
<td>23.133</td>
<td>26.407</td>
<td>26.867</td>
</tr>
<tr class="td">
<th class="th">28</th>
<td>19.777</td>
<td>20.598</td>
<td>24.015</td>
<td>23.634</td>
<td>24.073</td>
</tr>
<tr class="gtd">
<th class="gth">29</th>
<td>20.405</td>
<td><span class="ibb">
<b>19.084</b>
</span>
</td>
<td>20.059</td>
</tr>
<tr class="td">
<th class="th">30</th>
<td><span class="ibb">
<b>19.501</b>
</span>
</td>
<td>19.303</td>
<td>20.738</td>
</tr>
</tbody>
</table>

In [12]:
soup.find_all('table')[0]

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tbody align="right">
<tr>
<td align="center" colspan="7"><img alt="Club logo" src="exampleLogo.jpg"/></td>
</tr>
<tr class="ttd">
<td align="center" colspan="7">Power Racing Series</td>
</tr>
<tr>
<td align="center" colspan="7">2017 New York Sprint 2 Main 2017-09-23 15:07:22</td>
</tr>
<tr>
<td align="center" colspan="7">Lap</td>
</tr>
<tr>
<td align="center" colspan="7">Main</td>
</tr>
<tr>
<td>
<br>
</br></td>
</tr>
</tbody>
</table>

In [13]:
soup.find_all('table')[1]

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<thead align="right" class="hth">
<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>
</thead>
<tbody align="right">
<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>
<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>
<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>
<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>
<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>
<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>
<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>
<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>
<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>
<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>
<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>
<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>
<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>
<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>
<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>
<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>
<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>
<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>
</tbody>
</table>

In [14]:
results = soup.find_all('table')[1]

In [15]:
print(results)

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<thead align="right" class="hth">
<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>
</thead>
<tbody align="right">
<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>
<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>
<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>
<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>
<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>
<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>
<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>
<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>
<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>
<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>
<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>
<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>
<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>
<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>
<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>
<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>
<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>
<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>
</tbody>
</table>

In [16]:
for child in soup.find_all('table')[1].descendants:
    print(child)

<thead align="right" class="hth">
<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>
</thead>


<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>


<th>Position</th>
Position


<th>Laps</th>
Laps


<th>Time</th>
Time


<th>Average</th>
Average


<th>Best</th>
Best


<th>Laps Leading</th>
Laps Leading


<th>Name</th>
Name






<tbody align="right">
<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>
<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>
<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>
<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>
<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>
<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>
<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>
<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>
<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>
<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>
<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>
<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>
<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>
<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>
<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>
<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>
<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>
<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>
</tbody>


<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>


<td>1</td>
1


<td>30</td>
30


<td>11:20.014</td>
11:20.014


<td>22.667</td>
22.667


<td>30/19.501</td>
30/19.501


<td>11</td>
11


<td>Atomic Chibi</td>
Atomic Chibi




<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>


<td>2</td>
2


<td>30</td>
30


<td>11:22.749</td>
11:22.749


<td>22.758</td>
22.758


<td>29/19.084</td>
29/19.084


<td>8</td>
8


<td>Lego Car</td>
Lego Car




<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>


<td>3</td>
3


<td>30</td>
30


<td>11:36.034</td>
11:36.034


<td>23.201</td>
23.201


<td>2/19.707</td>
2/19.707


<td>0</td>
0


<td>RU Greasy</td>
RU Greasy




<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>


<td>4</td>
4


<td>28</td>
28


<td>11:29.735</td>
11:29.735


<td>24.633</td>
24.633


<td>17/21.990</td>
17/21.990


<td>0</td>
0


<td>The Bus</td>
The Bus




<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>


<td>5</td>
5


<td>28</td>
28


<td>11:34.684</td>
11:34.684


<td>24.81</td>
24.81


<td>23/22.117</td>
23/22.117


<td>0</td>
0


<td>Amazon Box</td>
Amazon Box




<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>


<td>6</td>
6


<td>27</td>
27


<td>11:36.440</td>
11:36.440


<td>25.794</td>
25.794


<td>10/22.462</td>
10/22.462


<td>0</td>
0


<td>Blue Meanie</td>
Blue Meanie




<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>


<td>7</td>
7


<td>27</td>
27


<td>11:39.702</td>
11:39.702


<td>25.915</td>
25.915


<td>15/19.236</td>
15/19.236


<td>2</td>
2


<td>Electric Koolaid Acid Test</td>
Electric Koolaid Acid Test




<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>


<td>8</td>
8


<td>22</td>
22


<td>11:26.011</td>
11:26.011


<td>31.182</td>
31.182


<td>4/26.520</td>
4/26.520


<td>0</td>
0


<td>MAV 721</td>
MAV 721




<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>


<td>9</td>
9


<td>21</td>
21


<td>11:35.918</td>
11:35.918


<td>33.139</td>
33.139


<td>14/31.678</td>
14/31.678


<td>0</td>
0


<td>Smoothie</td>
Smoothie




<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>


<td>10</td>
10


<td>20</td>
20


<td>11:43.065</td>
11:43.065


<td>35.153</td>
35.153


<td>13/30.852</td>
13/30.852


<td>0</td>
0


<td>Maximum Overdrive</td>
Maximum Overdrive




<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>


<td>11</td>
11


<td>19</td>
19


<td>11:34.858</td>
11:34.858


<td>36.571</td>
36.571


<td>18/20.315</td>
18/20.315


<td>0</td>
0


<td>FUBAR</td>
FUBAR




<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>


<td>12</td>
12


<td>16</td>
16


<td>8:15.778</td>
8:15.778


<td>30.986</td>
30.986


<td>9/25.756</td>
9/25.756


<td>0</td>
0


<td>Aerobot</td>
Aerobot




<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>


<td>13</td>
13


<td>15</td>
15


<td>11:36.035</td>
11:36.035


<td>46.402</td>
46.402


<td>7/28.310</td>
7/28.310


<td>0</td>
0


<td>Train Wrecks</td>
Train Wrecks




<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>


<td>14</td>
14


<td>15</td>
15


<td>11:40.800</td>
11:40.800


<td>46.72</td>
46.72


<td>7/31.890</td>
7/31.890


<td>0</td>
0


<td>Go Shopping Kart</td>
Go Shopping Kart




<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>


<td>15</td>
15


<td>11</td>
11


<td>5:36.293</td>
5:36.293


<td>30.572</td>
30.572


<td>4/23.936</td>
4/23.936


<td>0</td>
0


<td>LIVFREE</td>
LIVFREE




<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>


<td>16</td>
16


<td>9</td>
9


<td>3:28.135</td>
3:28.135


<td>23.126</td>
23.126


<td>2/18.296</td>
2/18.296


<td>9</td>
9


<td>Lightning McQueen</td>
Lightning McQueen




<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>


<td>17</td>
17


<td>1</td>
1


<td>33.660</td>
33.660


<td>33.66</td>
33.66


<td>2/999.000</td>
2/999.000


<td>0</td>
0


<td>ITSABert</td>
ITSABert




<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>


<td>18</td>
18


<td>1</td>
1


<td>7:23.381</td>
7:23.381


<td>443.381</td>
443.381


<td>4/999.000</td>
4/999.000


<td>0</td>
0


<td>The Chariot</td>
The Chariot

In [18]:
result_soup = BeautifulSoup(str(results), 'html.parser')

In [28]:
print(result_soup.prettify())

<table border="0" cellpadding="0" cellspacing="0" width="100%">
 <thead align="right" class="hth">
  <tr>
   <th>
    Position
   </th>
   <th>
    Laps
   </th>
   <th>
    Time
   </th>
   <th>
    Average
   </th>
   <th>
    Best
   </th>
   <th>
    Laps Leading
   </th>
   <th>
    Name
   </th>
  </tr>
 </thead>
 <tbody align="right">
  <tr>
   <td>
    1
   </td>
   <td>
    30
   </td>
   <td>
    11:20.014
   </td>
   <td>
    22.667
   </td>
   <td>
    30/19.501
   </td>
   <td>
    11
   </td>
   <td>
    Atomic Chibi
   </td>
  </tr>
  <tr class="gtd">
   <td>
    2
   </td>
   <td>
    30
   </td>
   <td>
    11:22.749
   </td>
   <td>
    22.758
   </td>
   <td>
    29/19.084
   </td>
   <td>
    8
   </td>
   <td>
    Lego Car
   </td>
  </tr>
  <tr>
   <td>
    3
   </td>
   <td>
    30
   </td>
   <td>
    11:36.034
   </td>
   <td>
    23.201
   </td>
   <td>
    2/19.707
   </td>
   <td>
    0
   </td>
   <td>
    RU Greasy
   </td>
  </tr>
  <tr class="gtd">
   <td>
    4
   </td>
   <td>
    28
   </td>
   <td>
    11:29.735
   </td>
   <td>
    24.633
   </td>
   <td>
    17/21.990
   </td>
   <td>
    0
   </td>
   <td>
    The Bus
   </td>
  </tr>
  <tr>
   <td>
    5
   </td>
   <td>
    28
   </td>
   <td>
    11:34.684
   </td>
   <td>
    24.81
   </td>
   <td>
    23/22.117
   </td>
   <td>
    0
   </td>
   <td>
    Amazon Box
   </td>
  </tr>
  <tr class="gtd">
   <td>
    6
   </td>
   <td>
    27
   </td>
   <td>
    11:36.440
   </td>
   <td>
    25.794
   </td>
   <td>
    10/22.462
   </td>
   <td>
    0
   </td>
   <td>
    Blue Meanie
   </td>
  </tr>
  <tr>
   <td>
    7
   </td>
   <td>
    27
   </td>
   <td>
    11:39.702
   </td>
   <td>
    25.915
   </td>
   <td>
    15/19.236
   </td>
   <td>
    2
   </td>
   <td>
    Electric Koolaid Acid Test
   </td>
  </tr>
  <tr class="gtd">
   <td>
    8
   </td>
   <td>
    22
   </td>
   <td>
    11:26.011
   </td>
   <td>
    31.182
   </td>
   <td>
    4/26.520
   </td>
   <td>
    0
   </td>
   <td>
    MAV 721
   </td>
  </tr>
  <tr>
   <td>
    9
   </td>
   <td>
    21
   </td>
   <td>
    11:35.918
   </td>
   <td>
    33.139
   </td>
   <td>
    14/31.678
   </td>
   <td>
    0
   </td>
   <td>
    Smoothie
   </td>
  </tr>
  <tr class="gtd">
   <td>
    10
   </td>
   <td>
    20
   </td>
   <td>
    11:43.065
   </td>
   <td>
    35.153
   </td>
   <td>
    13/30.852
   </td>
   <td>
    0
   </td>
   <td>
    Maximum Overdrive
   </td>
  </tr>
  <tr>
   <td>
    11
   </td>
   <td>
    19
   </td>
   <td>
    11:34.858
   </td>
   <td>
    36.571
   </td>
   <td>
    18/20.315
   </td>
   <td>
    0
   </td>
   <td>
    FUBAR
   </td>
  </tr>
  <tr class="gtd">
   <td>
    12
   </td>
   <td>
    16
   </td>
   <td>
    8:15.778
   </td>
   <td>
    30.986
   </td>
   <td>
    9/25.756
   </td>
   <td>
    0
   </td>
   <td>
    Aerobot
   </td>
  </tr>
  <tr>
   <td>
    13
   </td>
   <td>
    15
   </td>
   <td>
    11:36.035
   </td>
   <td>
    46.402
   </td>
   <td>
    7/28.310
   </td>
   <td>
    0
   </td>
   <td>
    Train Wrecks
   </td>
  </tr>
  <tr class="gtd">
   <td>
    14
   </td>
   <td>
    15
   </td>
   <td>
    11:40.800
   </td>
   <td>
    46.72
   </td>
   <td>
    7/31.890
   </td>
   <td>
    0
   </td>
   <td>
    Go Shopping Kart
   </td>
  </tr>
  <tr>
   <td>
    15
   </td>
   <td>
    11
   </td>
   <td>
    5:36.293
   </td>
   <td>
    30.572
   </td>
   <td>
    4/23.936
   </td>
   <td>
    0
   </td>
   <td>
    LIVFREE
   </td>
  </tr>
  <tr class="gtd">
   <td>
    16
   </td>
   <td>
    9
   </td>
   <td>
    3:28.135
   </td>
   <td>
    23.126
   </td>
   <td>
    2/18.296
   </td>
   <td>
    9
   </td>
   <td>
    Lightning McQueen
   </td>
  </tr>
  <tr>
   <td>
    17
   </td>
   <td>
    1
   </td>
   <td>
    33.660
   </td>
   <td>
    33.66
   </td>
   <td>
    2/999.000
   </td>
   <td>
    0
   </td>
   <td>
    ITSABert
   </td>
  </tr>
  <tr class="gtd">
   <td>
    18
   </td>
   <td>
    1
   </td>
   <td>
    7:23.381
   </td>
   <td>
    443.381
   </td>
   <td>
    4/999.000
   </td>
   <td>
    0
   </td>
   <td>
    The Chariot
   </td>
  </tr>
 </tbody>
</table>

In [31]:
print(result_soup.contents)

[<table border="0" cellpadding="0" cellspacing="0" width="100%">
<thead align="right" class="hth">
<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>
</thead>
<tbody align="right">
<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>
<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>
<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>
<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>
<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>
<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>
<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>
<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>
<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>
<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>
<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>
<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>
<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>
<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>
<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>
<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>
<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>
<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>
</tbody>
</table>]

In [32]:
for child in result_soup.children:
    print(child)

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<thead align="right" class="hth">
<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>
</thead>
<tbody align="right">
<tr>
<td>1</td>
<td>30</td>
<td>11:20.014</td>
<td>22.667</td>
<td>30/19.501</td>
<td>11</td>
<td>Atomic Chibi</td>
</tr>
<tr class="gtd">
<td>2</td>
<td>30</td>
<td>11:22.749</td>
<td>22.758</td>
<td>29/19.084</td>
<td>8</td>
<td>Lego Car</td>
</tr>
<tr>
<td>3</td>
<td>30</td>
<td>11:36.034</td>
<td>23.201</td>
<td>2/19.707</td>
<td>0</td>
<td>RU Greasy</td>
</tr>
<tr class="gtd">
<td>4</td>
<td>28</td>
<td>11:29.735</td>
<td>24.633</td>
<td>17/21.990</td>
<td>0</td>
<td>The Bus</td>
</tr>
<tr>
<td>5</td>
<td>28</td>
<td>11:34.684</td>
<td>24.81</td>
<td>23/22.117</td>
<td>0</td>
<td>Amazon Box</td>
</tr>
<tr class="gtd">
<td>6</td>
<td>27</td>
<td>11:36.440</td>
<td>25.794</td>
<td>10/22.462</td>
<td>0</td>
<td>Blue Meanie</td>
</tr>
<tr>
<td>7</td>
<td>27</td>
<td>11:39.702</td>
<td>25.915</td>
<td>15/19.236</td>
<td>2</td>
<td>Electric Koolaid Acid Test</td>
</tr>
<tr class="gtd">
<td>8</td>
<td>22</td>
<td>11:26.011</td>
<td>31.182</td>
<td>4/26.520</td>
<td>0</td>
<td>MAV 721</td>
</tr>
<tr>
<td>9</td>
<td>21</td>
<td>11:35.918</td>
<td>33.139</td>
<td>14/31.678</td>
<td>0</td>
<td>Smoothie</td>
</tr>
<tr class="gtd">
<td>10</td>
<td>20</td>
<td>11:43.065</td>
<td>35.153</td>
<td>13/30.852</td>
<td>0</td>
<td>Maximum Overdrive</td>
</tr>
<tr>
<td>11</td>
<td>19</td>
<td>11:34.858</td>
<td>36.571</td>
<td>18/20.315</td>
<td>0</td>
<td>FUBAR</td>
</tr>
<tr class="gtd">
<td>12</td>
<td>16</td>
<td>8:15.778</td>
<td>30.986</td>
<td>9/25.756</td>
<td>0</td>
<td>Aerobot</td>
</tr>
<tr>
<td>13</td>
<td>15</td>
<td>11:36.035</td>
<td>46.402</td>
<td>7/28.310</td>
<td>0</td>
<td>Train Wrecks</td>
</tr>
<tr class="gtd">
<td>14</td>
<td>15</td>
<td>11:40.800</td>
<td>46.72</td>
<td>7/31.890</td>
<td>0</td>
<td>Go Shopping Kart</td>
</tr>
<tr>
<td>15</td>
<td>11</td>
<td>5:36.293</td>
<td>30.572</td>
<td>4/23.936</td>
<td>0</td>
<td>LIVFREE</td>
</tr>
<tr class="gtd">
<td>16</td>
<td>9</td>
<td>3:28.135</td>
<td>23.126</td>
<td>2/18.296</td>
<td>9</td>
<td>Lightning McQueen</td>
</tr>
<tr>
<td>17</td>
<td>1</td>
<td>33.660</td>
<td>33.66</td>
<td>2/999.000</td>
<td>0</td>
<td>ITSABert</td>
</tr>
<tr class="gtd">
<td>18</td>
<td>1</td>
<td>7:23.381</td>
<td>443.381</td>
<td>4/999.000</td>
<td>0</td>
<td>The Chariot</td>
</tr>
</tbody>
</table>

In [36]:
results.find_all('tr')

[<tr>
 <th>Position</th>
 <th>Laps</th>
 <th>Time</th>
 <th>Average</th>
 <th>Best</th>
 <th>Laps Leading</th>
 <th>Name</th>
 </tr>, <tr>
 <td>1</td>
 <td>30</td>
 <td>11:20.014</td>
 <td>22.667</td>
 <td>30/19.501</td>
 <td>11</td>
 <td>Atomic Chibi</td>
 </tr>, <tr class="gtd">
 <td>2</td>
 <td>30</td>
 <td>11:22.749</td>
 <td>22.758</td>
 <td>29/19.084</td>
 <td>8</td>
 <td>Lego Car</td>
 </tr>, <tr>
 <td>3</td>
 <td>30</td>
 <td>11:36.034</td>
 <td>23.201</td>
 <td>2/19.707</td>
 <td>0</td>
 <td>RU Greasy</td>
 </tr>, <tr class="gtd">
 <td>4</td>
 <td>28</td>
 <td>11:29.735</td>
 <td>24.633</td>
 <td>17/21.990</td>
 <td>0</td>
 <td>The Bus</td>
 </tr>, <tr>
 <td>5</td>
 <td>28</td>
 <td>11:34.684</td>
 <td>24.81</td>
 <td>23/22.117</td>
 <td>0</td>
 <td>Amazon Box</td>
 </tr>, <tr class="gtd">
 <td>6</td>
 <td>27</td>
 <td>11:36.440</td>
 <td>25.794</td>
 <td>10/22.462</td>
 <td>0</td>
 <td>Blue Meanie</td>
 </tr>, <tr>
 <td>7</td>
 <td>27</td>
 <td>11:39.702</td>
 <td>25.915</td>
 <td>15/19.236</td>
 <td>2</td>
 <td>Electric Koolaid Acid Test</td>
 </tr>, <tr class="gtd">
 <td>8</td>
 <td>22</td>
 <td>11:26.011</td>
 <td>31.182</td>
 <td>4/26.520</td>
 <td>0</td>
 <td>MAV 721</td>
 </tr>, <tr>
 <td>9</td>
 <td>21</td>
 <td>11:35.918</td>
 <td>33.139</td>
 <td>14/31.678</td>
 <td>0</td>
 <td>Smoothie</td>
 </tr>, <tr class="gtd">
 <td>10</td>
 <td>20</td>
 <td>11:43.065</td>
 <td>35.153</td>
 <td>13/30.852</td>
 <td>0</td>
 <td>Maximum Overdrive</td>
 </tr>, <tr>
 <td>11</td>
 <td>19</td>
 <td>11:34.858</td>
 <td>36.571</td>
 <td>18/20.315</td>
 <td>0</td>
 <td>FUBAR</td>
 </tr>, <tr class="gtd">
 <td>12</td>
 <td>16</td>
 <td>8:15.778</td>
 <td>30.986</td>
 <td>9/25.756</td>
 <td>0</td>
 <td>Aerobot</td>
 </tr>, <tr>
 <td>13</td>
 <td>15</td>
 <td>11:36.035</td>
 <td>46.402</td>
 <td>7/28.310</td>
 <td>0</td>
 <td>Train Wrecks</td>
 </tr>, <tr class="gtd">
 <td>14</td>
 <td>15</td>
 <td>11:40.800</td>
 <td>46.72</td>
 <td>7/31.890</td>
 <td>0</td>
 <td>Go Shopping Kart</td>
 </tr>, <tr>
 <td>15</td>
 <td>11</td>
 <td>5:36.293</td>
 <td>30.572</td>
 <td>4/23.936</td>
 <td>0</td>
 <td>LIVFREE</td>
 </tr>, <tr class="gtd">
 <td>16</td>
 <td>9</td>
 <td>3:28.135</td>
 <td>23.126</td>
 <td>2/18.296</td>
 <td>9</td>
 <td>Lightning McQueen</td>
 </tr>, <tr>
 <td>17</td>
 <td>1</td>
 <td>33.660</td>
 <td>33.66</td>
 <td>2/999.000</td>
 <td>0</td>
 <td>ITSABert</td>
 </tr>, <tr class="gtd">
 <td>18</td>
 <td>1</td>
 <td>7:23.381</td>
 <td>443.381</td>
 <td>4/999.000</td>
 <td>0</td>
 <td>The Chariot</td>
 </tr>]

In [37]:
results.find_all('tr')[0]

<tr>
<th>Position</th>
<th>Laps</th>
<th>Time</th>
<th>Average</th>
<th>Best</th>
<th>Laps Leading</th>
<th>Name</th>
</tr>

In [38]:
len(results.find_all('tr'))

19

In [40]:
import pandas as pd

In [42]:
dir(pd)

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'MultiIndex',
 'NaT',
 'Panel',
 'Panel4D',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseList',
 'SparsePanel',
 'SparseSeries',
 'SparseTimeSeries',
 'Term',
 'TimeGrouper',
 'TimeSeries',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'WidePanel',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p8',
 '_np_version_under1p9',
 '_period',
 '_sparse',
 '_testing',
 '_version',
 'algos',
 'bdate_range',
 'compat',
 'computation',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'dependency',
 'describe_option',
 'eval',
 'ewma',
 'ewmcorr',
 'ewmcov',
 'ewmstd',
 'ewmvar',
 'ewmvol',
 'expanding_apply',
 'expanding_corr',
 'expanding_count',
 'expanding_cov',
 'expanding_kurt',
 'expanding_max',
 'expanding_mean',
 'expanding_median',
 'expanding_min',
 'expanding_quantile',
 'expanding_skew',
 'expanding_std',
 'expanding_sum',
 'expanding_var',
 'factorize',
 'fama_macbeth',
 'formats',
 'get_dummies',
 'get_option',
 'get_store',
 'groupby',
 'hard_dependencies',
 'hashtable',
 'index',
 'indexes',
 'infer_freq',
 'info',
 'io',
 'isnull',
 'json',
 'lib',
 'lreshape',
 'match',
 'melt',
 'merge',
 'missing_dependencies',
 'msgpack',
 'notnull',
 'np',
 'offsets',
 'ols',
 'option_context',
 'options',
 'ordered_merge',
 'pandas',
 'parser',
 'period_range',
 'pivot',
 'pivot_table',
 'plot_params',
 'pnow',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_msgpack',
 'read_pickle',
 'read_sas',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'reset_option',
 'rolling_apply',
 'rolling_corr',
 'rolling_count',
 'rolling_cov',
 'rolling_kurt',
 'rolling_max',
 'rolling_mean',
 'rolling_median',
 'rolling_min',
 'rolling_quantile',
 'rolling_skew',
 'rolling_std',
 'rolling_sum',
 'rolling_var',
 'rolling_window',
 'scatter_matrix',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'sparse',
 'stats',
 'test',
 'timedelta_range',
 'to_datetime',
 'to_msgpack',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tools',
 'tseries',
 'tslib',
 'types',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [44]:
header = results.find_all('tr')[0]

In [50]:
for item in header.children:
    print(item.string)

Position


Laps


Time


Average


Best


Laps Leading


Name

In [56]:
header = [item.string for item in results.find_all('tr')[0] if item.string != '\n']

In [57]:
print(header)

['Position', 'Laps', 'Time', 'Average', 'Best', 'Laps Leading', 'Name']

In [60]:
for row in results.find_all('tr'):
    clean_row = [item.string for item in row if item.string != '\n']
    print(clean_row)

['Position', 'Laps', 'Time', 'Average', 'Best', 'Laps Leading', 'Name']
['1', '30', '11:20.014', '22.667', '30/19.501', '11', 'Atomic Chibi']
['2', '30', '11:22.749', '22.758', '29/19.084', '8', 'Lego Car']
['3', '30', '11:36.034', '23.201', '2/19.707', '0', 'RU Greasy']
['4', '28', '11:29.735', '24.633', '17/21.990', '0', 'The Bus']
['5', '28', '11:34.684', '24.81', '23/22.117', '0', 'Amazon Box']
['6', '27', '11:36.440', '25.794', '10/22.462', '0', 'Blue Meanie']
['7', '27', '11:39.702', '25.915', '15/19.236', '2', 'Electric Koolaid Acid Test']
['8', '22', '11:26.011', '31.182', '4/26.520', '0', 'MAV 721']
['9', '21', '11:35.918', '33.139', '14/31.678', '0', 'Smoothie']
['10', '20', '11:43.065', '35.153', '13/30.852', '0', 'Maximum Overdrive']
['11', '19', '11:34.858', '36.571', '18/20.315', '0', 'FUBAR']
['12', '16', '8:15.778', '30.986', '9/25.756', '0', 'Aerobot']
['13', '15', '11:36.035', '46.402', '7/28.310', '0', 'Train Wrecks']
['14', '15', '11:40.800', '46.72', '7/31.890', '0', 'Go Shopping Kart']
['15', '11', '5:36.293', '30.572', '4/23.936', '0', 'LIVFREE']
['16', '9', '3:28.135', '23.126', '2/18.296', '9', 'Lightning McQueen']
['17', '1', '33.660', '33.66', '2/999.000', '0', 'ITSABert']
['18', '1', '7:23.381', '443.381', '4/999.000', '0', 'The Chariot']